# Generated by Django 2.1.1 on 2019-07-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='文章', max_length=32)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('createtime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '博客',
                'verbose_name': '博客',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='姓名', max_length=32)),
            ],
            options={
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='类别', max_length=32)),
            ],
            options={
                'verbose_name_plural': '类别',
                'verbose_name': '类别',
            },
        ),
        migrations.AddField(
            model_name='artical',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp0710.Author'),
        ),
        migrations.AddField(
            model_name='artical',
            name='type',
            field=models.ManyToManyField(to='myApp0710.Type'),
        ),
    ]
