# Generated by Django 2.1.1 on 2019-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp0710', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='picture',
            field=models.ImageField(default='images/nomal.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
